/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "name.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

int *
nodeproc_1(domain *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NODEPROC,
		(xdrproc_t) xdr_domain, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

domain *
nodeproc_2(domain *argp, CLIENT *clnt)
{
	static domain clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NODEPROC,
		(xdrproc_t) xdr_domain, (caddr_t) argp,
		(xdrproc_t) xdr_domain, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int *
nodeproc_3(domain *argp, CLIENT *clnt)
{
	static int clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NODEPROC,
		(xdrproc_t) xdr_domain, (caddr_t) argp,
		(xdrproc_t) xdr_int, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

domain *
nodeproc_4(domain *argp, CLIENT *clnt)
{
	static domain clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NODEPROC,
		(xdrproc_t) xdr_domain, (caddr_t) argp,
		(xdrproc_t) xdr_domain, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

domain *
nodeproc_5(domain *argp, CLIENT *clnt)
{
	static domain clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NODEPROC,
		(xdrproc_t) xdr_domain, (caddr_t) argp,
		(xdrproc_t) xdr_domain, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

domain *
nodeproc_6(domain *argp, CLIENT *clnt)
{
	static domain clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NODEPROC,
		(xdrproc_t) xdr_domain, (caddr_t) argp,
		(xdrproc_t) xdr_domain, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

domain *
nodeproc_7(domain *argp, CLIENT *clnt)
{
	static domain clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NODEPROC,
		(xdrproc_t) xdr_domain, (caddr_t) argp,
		(xdrproc_t) xdr_domain, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

domain *
nodeproc_8(domain *argp, CLIENT *clnt)
{
	static domain clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, NODEPROC,
		(xdrproc_t) xdr_domain, (caddr_t) argp,
		(xdrproc_t) xdr_domain, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
