/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NAME_H_RPCGEN
#define _NAME_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct domain {
	char content[64];
};
typedef struct domain domain;

#define DNSPROG 0x3012225
#define ROOT 1

#if defined(__STDC__) || defined(__cplusplus)
#define NODEPROC 1
extern  int * nodeproc_1(domain *, CLIENT *);
extern  int * nodeproc_1_svc(domain *, struct svc_req *);
extern int dnsprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define NODEPROC 1
extern  int * nodeproc_1();
extern  int * nodeproc_1_svc();
extern int dnsprog_1_freeresult ();
#endif /* K&R C */
#define NODE2 2

#if defined(__STDC__) || defined(__cplusplus)
extern  domain * nodeproc_2(domain *, CLIENT *);
extern  domain * nodeproc_2_svc(domain *, struct svc_req *);
extern int dnsprog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  domain * nodeproc_2();
extern  domain * nodeproc_2_svc();
extern int dnsprog_2_freeresult ();
#endif /* K&R C */
#define NODE3 3

#if defined(__STDC__) || defined(__cplusplus)
extern  int * nodeproc_3(domain *, CLIENT *);
extern  int * nodeproc_3_svc(domain *, struct svc_req *);
extern int dnsprog_3_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  int * nodeproc_3();
extern  int * nodeproc_3_svc();
extern int dnsprog_3_freeresult ();
#endif /* K&R C */
#define NODE4 4

#if defined(__STDC__) || defined(__cplusplus)
extern  domain * nodeproc_4(domain *, CLIENT *);
extern  domain * nodeproc_4_svc(domain *, struct svc_req *);
extern int dnsprog_4_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  domain * nodeproc_4();
extern  domain * nodeproc_4_svc();
extern int dnsprog_4_freeresult ();
#endif /* K&R C */
#define NODE5 5

#if defined(__STDC__) || defined(__cplusplus)
extern  domain * nodeproc_5(domain *, CLIENT *);
extern  domain * nodeproc_5_svc(domain *, struct svc_req *);
extern int dnsprog_5_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  domain * nodeproc_5();
extern  domain * nodeproc_5_svc();
extern int dnsprog_5_freeresult ();
#endif /* K&R C */
#define NODE6 6

#if defined(__STDC__) || defined(__cplusplus)
extern  domain * nodeproc_6(domain *, CLIENT *);
extern  domain * nodeproc_6_svc(domain *, struct svc_req *);
extern int dnsprog_6_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  domain * nodeproc_6();
extern  domain * nodeproc_6_svc();
extern int dnsprog_6_freeresult ();
#endif /* K&R C */
#define NODE7 7

#if defined(__STDC__) || defined(__cplusplus)
extern  domain * nodeproc_7(domain *, CLIENT *);
extern  domain * nodeproc_7_svc(domain *, struct svc_req *);
extern int dnsprog_7_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  domain * nodeproc_7();
extern  domain * nodeproc_7_svc();
extern int dnsprog_7_freeresult ();
#endif /* K&R C */
#define NODE8 8

#if defined(__STDC__) || defined(__cplusplus)
extern  domain * nodeproc_8(domain *, CLIENT *);
extern  domain * nodeproc_8_svc(domain *, struct svc_req *);
extern int dnsprog_8_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
extern  domain * nodeproc_8();
extern  domain * nodeproc_8_svc();
extern int dnsprog_8_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_domain (XDR *, domain*);

#else /* K&R C */
extern bool_t xdr_domain ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NAME_H_RPCGEN */
